Explicitly set oc-button:hover color & text-decoration
owncloud/owncloud-design-system pull request #1091
Opened 2021-02-16 14:31 UTC by pascalwengerter

Fixes #899 (but there's more to it, see details below)

I tested the changes locally editing the code preview on the [OcButton](http://localhost:6060/#/oC%20Components/OcButton), as

```html
  <oc-button variation="primary" class="oc-mr-s" type="a">Primary button (a)</oc-button>
  <oc-button variation="primary" class="oc-mr-s" type="button">Primary button (button)</oc-button>
```

Having resolved the `color` problem I realized that `text-decoration` differs between `type="a"` and `type="button"`, so I decided to explicitly set it to `none` (as this is the case with other button types in use).

Just now I made the mistake and did some further investigation since oc-buttons can also be `"danger"` or `"inverse"` (default), and there's more odd behaviour with `color`, `text-decoration` but also `font-family`? 🤯 

To reproduce (and open further issues), feel free to use the snippet below:

```html
<oc-button variation="danger" type="button" class="oc-mr-s">
  <oc-icon name="delete" aria-hidden="true" />
  Danger Button
</oc-button>
<oc-button variation="danger" type="a" class="oc-mr-s">
  <oc-icon name="delete" aria-hidden="true" />
  Danger Button
</oc-button>
```

2021-02-17 08:49 UTC, LukasHirt commented
Super weird that the font-family is changing with different variations. Anyway, thanks for taking care! Add a changelog item pls ([changelog readme](https://github.com/owncloud/owncloud-design-system/blob/master/changelog/README.md)) and I think we can merge this PR and take care of other issues in a separate one

2021-02-18 14:10 UTC, kulmann requested changes
The changelog in our projects is autogenerated, based on individual changelog files. Could you please place your changelog item in the `changelogs/unreleased` folder? https://github.com/owncloud/owncloud-design-system/tree/master/changelog/unreleased

Format of one changelog file is super simple: Title, description, list of links. Each of those categories separated by linebreaks.

2021-02-22 11:00 UTC, pascalwengerter commented
> The changelog in our projects is autogenerated, based on individual changelog files. Could you please place your changelog item in the `changelogs/unreleased` folder? https://github.com/owncloud/owncloud-design-system/tree/master/changelog/unreleased
> 
> Format of one changelog file is super simple: Title, description, list of links. Each of those categories separated by linebreaks.

@kulmann hope this one checks out? Is there a clear rule on squashing commits etc? :)

2021-02-22 11:00 UTC, kulmann approved these changes
👍

2021-02-22 11:03 UTC, kulmann commented
> > The changelog in our projects is autogenerated, based on individual changelog files. Could you please place your changelog item in the `changelogs/unreleased` folder? https://github.com/owncloud/owncloud-design-system/tree/master/changelog/unreleased
> > Format of one changelog file is super simple: Title, description, list of links. Each of those categories separated by linebreaks.
> 
> @kulmann hope this one checks out? Is there a clear rule on squashing commits etc? :)

We try to avoid squashing if possible and have small commits with reasonable messages for improved bisecting experience and easy reviews etc. I don't mind having reverts in the commit log.

2021-02-22 11:03 UTC, merged