Add label and messages to textarea inputs
owncloud/owncloud-design-system pull request #1144
Opened 2021-03-12 11:07 UTC by JammingBen

Similar to https://github.com/owncloud/owncloud-design-system/pull/1141:

* Remove placeholders
* Add required label to textareas
* Add optional description message to textareas
* Add aria-labelledby property which references the label element
* Add aria-describedby which either references the description (if given), or an error/warning (if given)
* Add aria-invalid property

Unfortunately there was no message line implemented yet, so I had to include this first.

2021-03-12 11:10 UTC, JanAckermann approved these changes

2021-03-15 13:28 UTC, JanAckermann commented on src/components/OcTextarea.vue
> +    <label :id="labelId" class="oc-label" :for="textareaId" v-text="label" />
do we still need the label id?

2021-03-15 13:30 UTC, kulmann commented on src/components/OcTextarea.vue
> +    <label :id="labelId" class="oc-label" :for="textareaId" v-text="label" />
Not needed anymore

2021-03-15 14:03 UTC, JanAckermann requested changes

2021-03-15 14:03 UTC, JanAckermann commented on src/components/OcTextarea.vue
> +    id: {
We have already an id here, replace the default with unique-id and rename old textareaId :+1:

2021-03-15 14:28 UTC, JanAckermann approved these changes

2021-03-15 15:36 UTC, kulmann requested changes
Could you introduce the new styles as a style tag within the `OcTextarea.vue` file (i.e. as a real single file component) instead of in a new scss file? You can do so by adding a `<style lang="scss"></style>` tag as third element (order is: `template`, `script`, `style`, `docs`).

2021-03-16 15:58 UTC, kulmann approved these changes

2021-03-16 15:58 UTC, merged