Add aria properties to radio input
owncloud/owncloud-design-system pull request #1148
Opened 2021-03-15 10:18 UTC by JanAckermann

Add **id** and **for** properties to label
Add **aria-checked**, **aria-labelledby,**  **aria-disabled** property to input

2021-03-15 13:47 UTC, JanAckermann commented
@kulmann, unfortunately, I found no possibility to set the checked property to the input element, I only can set it from outside the component,  set it inside the component, does not have any effect.

2021-03-16 13:12 UTC, kulmann requested changes

2021-03-16 13:12 UTC, kulmann commented on changelog/unreleased/radio-acessibility
> +Enhancement: Add aria properties to radio input
Please rename the changelog file to `enhancement-radio-accessibility` (add `enhancement-` prefix and fix typo in `accessibility`)

2021-03-16 13:12 UTC, kulmann commented on src/components/OcRadio.vue
> +  <span :class="{ 'oc-cursor-pointer': !disabled }">
You need to move the cursor class to the label. Having the oc-cursor-pointer class on the span, I don't see a pointer on the label, only on the radiobutton itself. Moving it to the label again works. Not needed on the input, as it already has the pointer by default.

2021-03-16 13:12 UTC, kulmann commented on src/components/OcRadio.vue
> +  <span :class="{ 'oc-cursor-pointer': !disabled }">
IMO it makes sense to move the classes of the label into a computed property then, since there are zero to two classes for the label.

2021-03-16 14:23 UTC, kulmann approved these changes
🚀

2021-03-16 14:23 UTC, merged