reduce fileslist row height
owncloud/owncloud-design-system pull request #1319
Opened 2021-05-21 15:18 UTC by tbsbdr

# description
issue: https://github.com/owncloud/web/issues/5078
**problem:** row height is limited by the sharing indicators.

this PR sets the row height to the minimum possible with the sharing-indicators still placed below the filename. it is meant as a quickfix to reduce the filelist-height.

please review carefully :-)

![image](https://user-images.githubusercontent.com/26610733/119160063-2bd1f300-ba58-11eb-80b9-155001aaccb9.png)
![image](https://user-images.githubusercontent.com/26610733/119160094-31c7d400-ba58-11eb-993b-89c28ecb44e2.png)
![image](https://user-images.githubusercontent.com/26610733/119160121-38eee200-ba58-11eb-95e9-4dd8fbc9792b.png)

2021-05-21 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/owncloud-design-system?pullRequest=1319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/owncloud-design-system?pullRequest=1319) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/owncloud-design-system?pullRequest=1319) it.</sub>

2021-05-25 06:53 UTC, pascalwengerter approved these changes
LGTM 🎨

2021-05-25 07:14 UTC, kulmann requested changes
Needs a changelog item 😁 Just copy one of the `enhancement` changelog items from the `changelog/unreleased` folder and change it according to the content of this PR.

2021-05-25 07:14 UTC, kulmann commented on src/components/table/_OcTableCell.vue
> +  padding: 0px var(--oc-space-xsmall);
```suggestion
  padding: 0 var(--oc-space-xsmall);
```

2021-05-25 07:14 UTC, kulmann commented on src/components/table/_OcTableCell.vue
> +  padding: 0px var(--oc-space-xsmall);
`0` is sufficient, doesn't need a unit.

2021-05-25 11:36 UTC, merged