Added unit tests for OcLoader component
owncloud/owncloud-design-system pull request #1449
Opened 2021-06-30 10:02 UTC by kiranparajuli589

## Description
Added unit tests for `OcLoader` component

## Related Issue

- Part of #1366 

## Motivation and Context

## How Has This Been Tested?

- 🤖 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:

- [ ] ...

2021-06-30 10:06 UTC, individual-it requested changes

2021-06-30 10:06 UTC, individual-it commented on src/components/OcLoader.spec.js
> +      console.log(wrapper.html())
please delete log output

2021-07-02 08:24 UTC, pascalwengerter approved these changes

2021-07-02 08:30 UTC, individual-it approved these changes

2021-07-02 08:30 UTC, merged