Add grouping functionality to OcTableFiles
owncloud/owncloud-design-system pull request #1641
Opened 2021-09-08 08:01 UTC by elizavetaRa

## Description
Grouping as well as preview functionality for the tables. 

Setup is done with the property "groupingSettings" . Following settings are possible:
- groupingFunctions: Object with keys as grouping options names and functions that get a table data row and return a group name for that row. The names of the functions are used as grouping options. 

- groupingBy: must be either one of the keys in groupingFunctions or 'None'. If not set, default grouping will be 'None'.
- ShowGroupingOptions: boolean value for showing or hinding the select element with grouping options above the table.
- PreviewAmount: Integer value that is used to show only the first n data rows of the table.object

![Screenshot from 2021-09-08 10-47-39](https://user-images.githubusercontent.com/7430156/132478203-38f7ef88-78a8-4591-a7cf-7ede8356a436.png)

## Related Issue

## Motivation and Context
UX-friendly option to make the table more

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:

- Tests

2021-09-08 08:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/owncloud-design-system?pullRequest=1641) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/owncloud-design-system?pullRequest=1641) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/owncloud-design-system?pullRequest=1641) it.</sub>

2021-09-17 13:30 UTC, labkode commented
Plese merge is green before we get into conflicts

2021-09-17 13:42 UTC, kulmann requested changes
This PR does two things, please split it into two PRs:
1: different icon variation for files vs folders
2: grouping for files table. BUT: the actual grouping logic for the `OcTable` is completely missing from this PR.

Without having seen the grouping implementation yet, please also:
a: add extensive units tests for your new grouping functionality
b: add custom prop validation for the grouping prop

I can see line break changes in you PR - are they necessary? Would be good to reduce that kind of noise in PRs.

Lastly, please accept the CLA, otherwise we can't merge your contribution.

Please get in touch with me if you need help in any way. Happy to assist!

2021-09-17 13:42 UTC, kulmann commented on src/components/table/OcTableFiles.vue
> +    groupingSettings: {
I'd prefer `grouping` as prop name. `groupingSettings` sounds too verbose.

2021-09-17 16:10 UTC, pascalwengerter commented on src/components/table/OcTableFiles.vue
> -      <oc-avatars
This looks like you haven't properly rebased your PR - the `oc-avatar-group` has been replaced by a (new) `oc-avatars` component which expects an `items` prop and not the (old) `users`

2021-09-17 16:11 UTC, pascalwengerter requested changes

2021-09-17 16:11 UTC, pascalwengerter commented on src/components/table/OcTableFiles.vue
> -  import { shareType } from "../../utils/shareType"
This also is on (our) current master and looks like you're running an outdated version. Please rebase on our master and apply your changes there

2021-11-07 14:22 UTC, diocas commented
Let's close this PR as this shouldn't be trying to merge our QA branch which has other stuff... Let's discuss it tomorrow and do a different PR for these things... @elizavetaRa

2021-11-08 07:56 UTC, closed without merging