Truncate file names while preserving file extensions
owncloud/owncloud-design-system pull request #1782
Opened 2021-11-16 13:50 UTC by JammingBen

## Related Issue

- [Fixes <issue_link>](https://jira.owncloud.com/browse/WEB-1026)

## Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/50302941/141997373-bfa4f55d-8f4b-4c9b-8ff0-018b9cceaad0.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:

- [ ] ...

2021-11-16 13:57 UTC, JammingBen commented
A few notes/questions:

* Do we want to separate the file name and the extension, e.g. by using the muted class on the extension? OC10 currently does this:
![image](https://user-images.githubusercontent.com/50302941/141997758-3600d4f8-9572-4566-a0cf-90ab5bbfd3bd.png)
* Do we want to have tooltips on truncated file names? The issue I see here is that we can't determine if a file name is being truncated or not. So we'd have to implement tooltips for all file names.
* With very long folder paths, the filename will not be displayed at all. It was like this before, and I don't see an easy way to overcome this, but I want to point it out. It can be kinda confusing now with the file extension showing at the end.
![image](https://user-images.githubusercontent.com/50302941/141997601-54349ea6-801b-4f0c-ad99-d7bfeff2d9bf.png)

@kulmann @pascalwengerter Any opinions here?

2021-11-18 09:20 UTC, fschade commented
@JammingBen just an idea, if we have a path in the resource name, can we create 3 containers?
(a/very/long/pa...)(aLongFileNa....)(.ext)

2021-11-18 09:24 UTC, JammingBen commented
Actually it is already divided in 3 containers. But as mentioned above, in the near future we will have the path beneath the file name (https://github.com/owncloud/web/issues/5953) anyway, so we problem becomes kinda obsolete IMO.

2021-11-24 08:17 UTC, kulmann requested changes

2021-11-24 08:18 UTC, kulmann commented on src/components/atoms/OcResourceName/OcResourceName.vue
> +    <span v-if="extension" class="oc-resource-extension" v-text="displayExtension" />
FYI what we need at the same time, is, that actual whitespace in the filenames gets preserved. We had a solution in the past without `white-space: pre` and that trimmed all leading and trailing whitespace from the spans.

2021-11-24 09:28 UTC, JammingBen commented on src/components/atoms/OcResourceName/OcResourceName.vue
> +    <span v-if="extension" class="oc-resource-extension" v-text="displayExtension" />
Played around with it, but this does not seem to work :( Tried both via one line and CSS. I think we would need to implement some custom solution to make this work properly.

2021-11-25 19:02 UTC, kulmann commented on src/components/atoms/OcResourceName/OcResourceName.vue
> +    <span v-if="extension" class="oc-resource-extension" v-text="displayExtension" />
How'd you like to continue with this? the screenshot that I posted is too much of a regression in my opinion.

2021-11-26 07:26 UTC, JammingBen commented on src/components/atoms/OcResourceName/OcResourceName.vue
> +    <span v-if="extension" class="oc-resource-extension" v-text="displayExtension" />
I'll do another test with a custom after element. If that doesn't work, the only option I see is to implement a custom solution. I don't know yet how that could look like, maybe calculate the max number of characters based on the current width of the table cell?

2021-11-29 13:11 UTC, tbsbdr commented on src/components/atoms/OcResourceName/OcResourceName.vue
> +    <span v-if="extension" class="oc-resource-extension" v-text="displayExtension" />
i would go with 1) as well

2021-11-29 15:29 UTC, kulmann approved these changes

2021-11-29 15:29 UTC, merged