Draft: Extract sort handling from OcTable
owncloud/owncloud-design-system pull request #1825
Opened 2021-12-12 17:08 UTC by dschmidt

## Description
The sorting depends on the structure of resources which do not exist in ODS but only in web-app-files.
Moreover, we need to sort before pagination and as pagination is not handled in `OcTable` either, we need to handle sorting externally as well.
This has the additional benefit that this prepares us better for retrieving server sorted and paginated resources.

This is a draft and as such has a few rough edges.
For instance sorting has been added to the first example of `OcTable`, should we get this close to merging this would deserve its own section obviously :) 

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:

- [ ] ...

2021-12-13 10:04 UTC, pascalwengerter requested changes
Would love to have a link/note to this PR in the "extract OcTableFiles" change changelog item :)

2021-12-13 10:31 UTC, pascalwengerter commented
@dschmidt what's necessary to get this merged? We could easily to that and release another pre-release of the ODS and use that in `web`

2021-12-13 11:02 UTC, kulmann commented on src/mixins/sort.js
> +      // FIXME: asc or desc or nothing
i.e. add a validator, right? ;-)

2021-12-13 11:13 UTC, dschmidt commented
> @dschmidt what's necessary to get this merged? We could easily to that and release another pre-release of the ODS and use that in `web`

Not much, I would just like to have my web pr closer to merging before we merge this

2021-12-20 14:00 UTC, kulmann approved these changes
LGTM 👍  and +1 for adding a sorting example 😇

2021-12-20 14:00 UTC, merged