Pass folderLink to OCResource component
owncloud/owncloud-design-system pull request #1913
Opened 2022-01-28 13:20 UTC by JanAckermann

## Description
Change: Pass folderLink to OcResource component

For more flexibility, the folderLink needs to be passed to the OcResource component

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:

- [ ] ...

2022-01-28 13:28 UTC, pascalwengerter requested changes
Please only merge when the corresponding PR in `web` is close to its finalization to not block the ODS in the meantime 🤓

2022-02-03 12:47 UTC, kulmann reviewed
OcResource has a `parentFolderLinkPath` and a `folderLink` which previously both relied on the target route. Adding one property for each seems weird. What about passing a callback instead which handles building a router link from a resource path?

2022-02-03 14:58 UTC, pascalwengerter commented on package.json
> +  "version": "12.0.0-alpha.22",
Sollte nicht mit gemerged werden:)

2022-02-03 15:06 UTC, pascalwengerter approved these changes
Should be good to go

2022-02-03 15:10 UTC, merged