New icons for resource types
owncloud/owncloud-design-system pull request #2005
Opened 2022-03-04 12:01 UTC by elizavetaRa

## Description
- drawio
- ifc

2022-03-04 12:04 UTC, elizavetaRa commented
@tbsbdr @pascalwengerter @kulmann Guys, ping me if there are any other icons that are needed. We also have a jsroot icon, I don't know if it is needed upstream. And ping if some properties inside svg's need to be set in some other way.

2022-03-04 18:18 UTC, diocas commented
@elizavetaRa jupyter? def is more common than ifc

2022-03-07 09:46 UTC, pascalwengerter requested changes
Feature branch would need a review, merge & rebase with changes in https://github.com/cernbox/owncloud-design-system/pull/222 included. Then I'm happy to proceed very quickly here :)

2022-03-07 15:11 UTC, pascalwengerter requested changes
Please omit the colors from the SVG, they will later be replaced by `var(--oc-color-icon-ifc)` according to the mapping we implemented (and make sure the color you desire is the right one in the color.yaml file)

2022-03-07 15:11 UTC, pascalwengerter commented on src/assets/icons/resource-type-jupyter-fill.svg
> +      style="mix-blend-mode:normal;fill:#f37726;stroke-width:5.44357"
```suggestion
      style="mix-blend-mode:normal;stroke-width:5.44357"
```

2022-03-07 15:11 UTC, pascalwengerter commented on src/assets/icons/resource-type-jupyter-fill.svg
> +      style="mix-blend-mode:normal;fill:#f37726;stroke-width:5.44357"
```suggestion
      style="mix-blend-mode:normal;stroke-width:5.44357"
```

2022-03-14 16:25 UTC, merged