Fix tooltips overflowing on long words
owncloud/owncloud-design-system pull request #2137
Opened 2022-05-12 12:55 UTC by javfg

This PR fixes long words or paths breaking the tooltips in the sidebar:

![image](https://user-images.githubusercontent.com/6058151/168079139-d00351d6-91de-41fe-8606-5248d31fbc57.png)

By adding a `word-wrap: break-word` to the tippy content.

![image](https://user-images.githubusercontent.com/6058151/168079330-b88bea29-66f9-4f06-a8c6-2115e12b74d3.png)

This along with ellipsizing the paths will remove the scrollbar from the sidebar.

2022-05-12 12:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/owncloud-design-system?pullRequest=2137) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/owncloud-design-system?pullRequest=2137) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/owncloud-design-system?pullRequest=2137) it.</sub>

2022-05-16 09:35 UTC, pascalwengerter requested changes
Could you move the style rules into a separate tooltip.scss or tippy.scss file in `src/styles/theme`? I'm happy to approve&merge, but this does not (only) apply to OcDrop components, but is rather targeted at the tooltip directive :)

2022-05-16 09:36 UTC, pascalwengerter commented
Also, please add a changelog item;)

2022-05-16 10:58 UTC, javfg commented
@pascalwengerter Thanks for the suggestions! I've made the requested changes.

2022-05-16 12:04 UTC, pascalwengerter approved these changes
Thanks!

2022-05-16 12:04 UTC, pascalwengerter commented on changelog/unreleased/bugfix-tooltip-break-word
> +We've added word wrapping to the tippy tooltips so they handle very long paths properly.
Technically they handle all long strings properly :P but that should be fine

2022-05-16 12:04 UTC, merged