Nested drop functionality
owncloud/owncloud-design-system pull request #2239
Opened 2022-07-06 08:09 UTC by elizavetaRa

## Description
Adds "isNested" property to ocDrop that prevents the parent drop from hiding (not fires hideAll() in onShow() of child drop)

## Related Issue

- Fixes https://github.com/owncloud/owncloud-design-system/issues/2238

## Motivation and Context
Useful to create submenus

## Screenshots (if appropriate):
![ocDrop](https://user-images.githubusercontent.com/7430156/177501937-63ef0ad8-24a0-4aac-9336-25a5c2ac4fed.gif)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [] Documentation added/updated

2022-07-06 08:56 UTC, kulmann reviewed
Hm 🤔 Wouldn't that keep other opened OcDrop instances open as well if you open any other OcDrop that has `isNested=true`?

2022-07-06 08:56 UTC, kulmann commented on src/components/atoms/OcDrop/OcDrop.vue
> +      ...(!isNested && {
Why not like this?
```suggestion
      ...(!this.isNested && {
```

2022-07-06 11:39 UTC, elizavetaRa commented
> Hm thinking Wouldn't that keep other opened OcDrop instances open as well if you open any other OcDrop that has `isNested=true`?

@kulmann The parent  (grand...parent by nesting with more levels) ocDrop should not have "isNested" then all the other ocDrop insances get closed on show of the parent. 

I checked as alternative way if hideAll() has an option to exclude more tippy-elements, then it would be possible to hide all but current element and it's parent. But it seems like not. 

If you have any suggestions how to implement submenus otherwise, I am glad to do it :) We at CERNBox need this functionality to show several links in user menu under menu item "Useful links"

2022-07-06 11:48 UTC, kulmann requested changes

2022-07-06 11:48 UTC, kulmann commented on src/components/atoms/OcDrop/OcDrop.vue
> +    let isNested = this.isNested
line can be removed, now that you use `this.isNested` below

2022-07-06 11:49 UTC, kulmann commented
> @kulmann The parent (grand...parent by nesting with more levels) ocDrop should not have "isNested" then all the other ocDrop insances get closed on show of the parent.

Well... true 😅 This is fine then. :-) Had one more comment about one line that can be removed now. Otherwise good 👍

2022-07-06 11:56 UTC, kulmann approved these changes
👍

2022-07-11 07:43 UTC, pascalwengerter reviewed
Found a minor changelog thing which I'll fix after merging

2022-07-11 07:43 UTC, pascalwengerter commented on changelog/13.1.0_2022-06-07/enhancement-add-nested-drop
> +Enhancement: Add nestedd drop functionality
Sry, could you move this to the `unreleased` changelog folder?

2022-07-11 07:43 UTC, merged