Small design tweaks
owncloud/owncloud-design-system pull request #890
Opened 2020-09-29 17:53 UTC by LukasHirt

2020-10-01 10:56 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-01 11:07 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-01 11:15 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-01 11:20 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-01 11:20 UTC, micbar commented on src/styles/theme/oc-spinner.scss
> +  @include oc-spinner-size(1);
Codacy found an issue: [Expected blockless @include to come before rule (order/order)](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785)

2020-10-01 11:24 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-01 11:24 UTC, micbar commented on src/styles/theme/oc-spinner.scss
> +  @include oc-spinner-size(1);
Codacy found an issue: [Expected blockless @include to come before rule (order/order)](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785)

2020-10-01 12:19 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-01 15:18 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 08:27 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 08:36 UTC, kulmann requested changes

2020-10-02 08:36 UTC, kulmann commented on src/elements/OcSidebarNavItem.vue
> +        classes.push("oc-mt-m")
Can be `oc-mt` because that's already medium

2020-10-02 08:36 UTC, kulmann commented on src/styles/theme/oc-alert.scss
> +  transform: translateY(-space-medium);
misses the `$` sign for the variable

2020-10-02 08:36 UTC, kulmann commented on src/styles/theme/oc-app-menu.scss
> +  @extend .oc-mt-m;
Can be `oc-mt` (already medium by default)

2020-10-02 08:53 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 08:59 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 09:05 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 09:08 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 09:10 UTC, kulmann approved these changes
🚀

2020-10-02 09:20 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 09:24 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 09:51 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 10:16 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 10:22 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 12:53 UTC, micbar commented on src/styles/theme/oc-checkbox.scss
> +  -webkit-appearance: none;
Codacy found an issue: [Expected -webkit-appearance to come before vertical-align (order/properties-alphabetical-order)](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785)

2020-10-02 12:53 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 15:09 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-02 15:09 UTC, micbar commented on src/styles/theme/oc-checkbox.scss
> +  -webkit-appearance: none;
Codacy found an issue: [Expected -webkit-appearance to come before vertical-align (order/properties-alphabetical-order)](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785)

2020-10-03 03:46 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-03 03:46 UTC, micbar commented on src/styles/theme/oc-checkbox.scss
> +  -webkit-appearance: none;
Codacy found an issue: [Expected -webkit-appearance to come before vertical-align (order/properties-alphabetical-order)](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785)

2020-10-03 03:50 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-03 04:32 UTC, micbar commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utils/sizeClasses.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/owncloud-design-system/pullRequest?prid=6255785&bid=20370810)

2020-10-03 04:32 UTC, merged